# Generated by Django 2.2.2 on 2019-07-05 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='type',
            field=models.CharField(choices=[('PHONE', 'PHONE'), ('FACEBOOK', 'FACEBOOK'), ('EMAIL', 'EMAIL')], default='', max_length=64),
        ),
        migrations.AlterField(
            model_name='contact',
            name='value',
            field=models.CharField(default='', max_length=64),
        ),
        migrations.DeleteModel(
            name='ContactValue',
        ),
    ]
