# Generated by Django 2.2.2 on 2019-06-28 05:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_auto_20190628_1142'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contactvalue',
            old_name='name',
            new_name='value',
        ),
    ]
