# Generated by Django 2.2.2 on 2019-06-28 05:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_auto_20190628_1143'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contactvalue',
            name='value',
        ),
    ]
